### PR TITLE
(origin) Check installed version before updating

### PR DESCRIPTION
**Pull request by tylerszabo**

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
@tylerszabo any chance you would be able to make the necessary changes according to my review.

Would love to get this PR in before the next update of origin

**Comment by tylerszabo** [comment]
I'll update with the changes, would you like me to push --force or add another commit (it can be squashed when finishing PR)

**Comment by AdmiringWorm** [comment]
Just do what you want to. While I'll admit I usually prefer rebased PR's, it doesn't really matter either way for this repo.

**Comment by tylerszabo** [comment]
Tested with `cuninst -n origin; cinst origin`

**Comment by AdmiringWorm** [comment]
I'll need to make a small change to the update script when I merge this in. Just waiting for the appveyor build to complete first though.

**Comment by AdmiringWorm** [comment]
Thank you for your contributions, this will be made available when the next version of origin comes around.

**Comment by tylerszabo** [comment]
My pleasure - thanks for maintaining this (and so many other) packages :)

**Pull request merged**
