### PR TITLE
Origin upgrade consistently fails for me

### PR DESCRIPTION
**Pull request by pauby**
The Origin install consistently fails as the `OriginWebHelper` service appears to lock the files so they cannot be updated. When that issue is resolved the function `Uninstall-ChocolateyZipPackage` then fails as I'm assuming some of the files it is trying to remove are no longer there. 

1. I've added a `chocolateyBeforeModify.ps1` file to stop the `OriginWebHelper` process if it's running;
2. I've removed the code that uninstalls the zip package - the function `Uninstall-ChocolateyZipPackage` doesn't have `ErrorAction` parameter and I don't like wrapping in a `try{}` and empty `catch{}`. Most packages don't clean up after themselves so this isn't a huge problem but not ideal;

Thoughts?

### CODE REVIEW

**Comment by pauby** [comment]
@AdmiringWorm The AppVeyor is not failing because of my PR - there are modules missing. The messages says review it before asking for a human reviewer so I thought I'd let you know.

**Comment by AdmiringWorm** [comment]
thanks, I'll have a look at this. Unfortunately I won't be able to do that until wednesday, btw have you tried to for upgrading? The uninstallation of the previous software was needed in the past otherwise the installation would fail (and not because there was a service running already).

**Comment by pauby** [comment]
Over the last few weeks I've done a `choco upgrade` and every time without fail the Origin package gives me 'Access denied' errors. The only time it doesn't is when the `OriginWebHelper` service is stopped.

I did see the uninstallation was in the install file but it doesn't seem to make any difference, at least on my system. If it works fine on yours then I'm not sure what is happening.

**Comment by AdmiringWorm** [comment]
It could be that it only was necessary in an earlier version, if it works then that's great.

**Pull request merged**
