### PR TITLE
Fix InnoSetup and update

### PR DESCRIPTION
**Pull request by sharkykh**
Hopefully I did this correctly. Please let me know if have to do anything else.
(Not sure when I should commit `[AU innosetup]`?)

This fixes two issues:
1. Since the release of InnoSetup version 6 the files weren't being matched.
    There are only unicode releases now, and they're not tagged with `-unicode`.
	[From the changelog](http://www.jrsoftware.org/files/is6-whatsnew.htm):
	> Starting with Inno Setup 6 there's only one version available: Unicode Inno Setup.
2. I was getting the following message when updating, and it seemed like `innosetup.json` was missing `major-5`, so I used `$au_Force = $true` which added it, and I removed `major-6` before updating with `$au_Force = $false`.
```
*** Stream: major-5 ***
WARNING: Invalid nuspec file Version '' - using 0.0
URL check
  http://files.jrsoftware.org/is/5/innosetup-5.6.1.exe
nuspec version: 0.0
remote version: 5.6.1
New version is available but it already exists in the Chocolatey community feed (disable using $NoCheckChocoVersion):
  https://chocolatey.org/packages/innosetup/5.6.1
Package updated
```

### CODE REVIEW

**Comment by sharkykh** [comment]
I don't understand the warning on the failing tests.

<details>
<summary>Details</summary>

```
======================================================================================================================================================================================================================================
                                                                                                  START CHOCOLATEY UNINSTALL COMMAND
======================================================================================================================================================================================================================================
Chocolatey v0.10.8
Uninstalling the following packages:
innosetup
InnoSetup v6.0.2.20190616
WARNING: @{Inno Setup: Setup Version=5.5.9 (u); Inno Setup: App Path=C:\Program Files (x86)\Inno Setup 5; InstallLocation=C:\Program Files (x86)\Inno Setup 5\; Inno Setup: Icon Group=Inno Setup 5; Inno Setup: User=appveyor; Inno Setup: Selected Tasks=fileassoc; Inno Setup: Deselected Tasks=desktopicon; Inno Setup: Language=english; DisplayName=Inno Setup version 5.5.9; DisplayIcon=C:\Program Files (x86)\Inno Setup 5\Compil32.exe; UninstallString="C:\Program Files (x86)\Inno Setup 5\unins000.exe"; QuietUninstallString="C:\Program Files (x86)\Inno Setup 5\unins000.exe" /SILENT; DisplayVersion=5.5.9; Publisher=jrsoftware.org; URLInfoAbout=http://www.innosetup.com/; HelpLink=http://www.innosetup.com/; URLUpdateInfo=http://www.innosetup.com/; NoModify=1; NoRepair=1; InstallDate=20170831; MajorVersion=5; MinorVersion=5; VersionMajor=5; VersionMinor=5; EstimatedSize=6639; Inno Setup CodeFile: ISPP=1; PSPath=Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Inno Setup 5_is1; PSParentPath=Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall; PSChildName=Inno Setup 5_is1; PSProvider=Microsoft.PowerShell.Core\Registry} @{Inno Setup: Setup Version=6.0.2 (u); Inno Setup: App Path=C:\Testing\Inno Setup; InstallLocation=C:\Testing\Inno Setup\; Inno Setup: Icon Group=Inno Setup; Inno Setup: No Icons=1; Inno Setup: User=appveyor; Inno Setup: Selected Tasks=desktopicon; Inno Setup: Deselected Tasks=fileassoc; Inno Setup: Language=english; DisplayName=Inno Setup version 6.0.2; DisplayIcon=C:\Testing\Inno Setup\Compil32.exe; UninstallString="C:\Testing\Inno Setup\unins000.exe"; QuietUninstallString="C:\Testing\Inno Setup\unins000.exe" /SILENT; DisplayVersion=6.0.2; Publisher=jrsoftware.org; URLInfoAbout=http://www.innosetup.com/; HelpLink=http://www.innosetup.com/; URLUpdateInfo=http://www.innosetup.com/; NoModify=1; NoRepair=1; InstallDate=20190616; MajorVersion=6; MinorVersion=0; VersionMajor=6; VersionMinor=0; EstimatedSize=12953; PSPath=Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Inno Setup 6_is1; PSParentPath=Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall; PSChildName=Inno Setup 6_is1; PSProvider=Microsoft.PowerShell.Core\Registry}.Count matches found!
WARNING: To prevent accidental data loss, no programs will be uninstalled.
WARNING: Please alert package maintainer the following keys were matched:
WARNING: - @{Inno Setup: Setup Version=5.5.9 (u); Inno Setup: App Path=C:\Program Files (x86)\Inno Setup 5; InstallLocation=C:\Program Files (x86)\Inno Setup 5\; Inno Setup: Icon Group=Inno Setup 5; Inno Setup: User=appveyor; Inno Setup: Selected Tasks=fileassoc; Inno Setup: Deselected Tasks=desktopicon; Inno Setup: Language=english; DisplayName=Inno Setup version 5.5.9; DisplayIcon=C:\Program Files (x86)\Inno Setup 5\Compil32.exe; UninstallString="C:\Program Files (x86)\Inno Setup 5\unins000.exe"; QuietUninstallString="C:\Program Files (x86)\Inno Setup 5\unins000.exe" /SILENT; DisplayVersion=5.5.9; Publisher=jrsoftware.org; URLInfoAbout=http://www.innosetup.com/; HelpLink=http://www.innosetup.com/; URLUpdateInfo=http://www.innosetup.com/; NoModify=1; NoRepair=1; InstallDate=20170831; MajorVersion=5; MinorVersion=5; VersionMajor=5; VersionMinor=5; EstimatedSize=6639; Inno Setup CodeFile: ISPP=1; PSPath=Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Inno Setup 5_is1; PSParentPath=Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall; PSChildName=Inno Setup 5_is1; PSProvider=Microsoft.PowerShell.Core\Registry}.DisplayName
WARNING: - @{Inno Setup: Setup Version=6.0.2 (u); Inno Setup: App Path=C:\Testing\Inno Setup; InstallLocation=C:\Testing\Inno Setup\; Inno Setup: Icon Group=Inno Setup; Inno Setup: No Icons=1; Inno Setup: User=appveyor; Inno Setup: Selected Tasks=desktopicon; Inno Setup: Deselected Tasks=fileassoc; Inno Setup: Language=english; DisplayName=Inno Setup version 6.0.2; DisplayIcon=C:\Testing\Inno Setup\Compil32.exe; UninstallString="C:\Testing\Inno Setup\unins000.exe"; QuietUninstallString="C:\Testing\Inno Setup\unins000.exe" /SILENT; DisplayVersion=6.0.2; Publisher=jrsoftware.org; URLInfoAbout=http://www.innosetup.com/; HelpLink=http://www.innosetup.com/; URLUpdateInfo=http://www.innosetup.com/; NoModify=1; NoRepair=1; InstallDate=20190616; MajorVersion=6; MinorVersion=0; VersionMajor=6; VersionMinor=0; EstimatedSize=12953; PSPath=Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Inno Setup 6_is1; PSParentPath=Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall; PSChildName=Inno Setup 6_is1; PSProvider=Microsoft.PowerShell.Core\Registry}.DisplayName
Removing shim C:\ProgramData\chocolatey\bin\ISCC.exe which pointed to ''.
 Running auto uninstaller...
 Auto uninstaller has successfully uninstalled InnoSetup or detected previous uninstall.
 InnoSetup has been successfully uninstalled.
Chocolatey uninstalled 1/1 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
======================================================================================================================================================================================================================================
                                                                                                   END CHOCOLATEY UNINSTALL COMMAND
======================================================================================================================================================================================================================================
      [+] Should uninstall package after creating configuration file 9.27s
      [-] Should have removed directory used in configuration file 4ms
        Expected path 'C:\Testing\Inno Setup' to not exist, but it did exist.
        90:       "C:\Testing\Inno Setup" | Should -Not -Exist
        at <ScriptBlock>, C:\projects\chocolatey-packages-6y1im\automatic\innosetup\package.Tests.ps1: line 90
      [+] Should have removed desktop icon after uninstall 5ms
```

</details>

**Comment by AdmiringWorm** [comment]
@sharkykh thank you for opening this Pull Request, unfortunately I can not accept it as is.
The reason is because there have been made changes to files that don`t need to be changed, and some that shouldn`t be changed manually.

For this PR, the only files that should be changed as part of it is the `update.ps1` and `package.Tests.ps1` files.

I will make the necessary changes (and add you as a co-maintainer in the commit) for what needs to be changed a little later today.

But in the meantime, let me answer some of your comments:

> (Not sure when I should commit [AU innosetup]?)

You shouldn`t, this is only to be used when there is a need to push a fix version of a package and not a normal version.

> I was getting the following message when updating, and it seemed like innosetup.json was missing major-5, so I used $au_Force = $true which added it, and I removed major-6 before updating with $au_Force = $false.

This is intentional, the `major-5` stream would only be added if I create a fix version, or if there is a new version for the `5.x` versions (when the `6.x` versions is catched as the latest).
There is also no need to remove the `major-6` stream as well. TBH, that file should only be touched when a package gets updated, and not as part of a PR.

> I don't understand the warning on the failing tests.

All of the warnings shown there are related, it seems chocolatey somehow is unable to uninstall the `5.x` range of the inno setup installer (or maybe it is because appveyor already have it installed, so it detects multiple versions installed).

This is a change I need to make to the building of Pull Requests, so I can ensure that inno setup isn`t already installed.

**Comment by AdmiringWorm** [comment]
The necessary changes is now committed to the develop branch here: https://github.com/AdmiringWorm/chocolatey-packages/commit/d27b9b171942f47cfcb069406f1fceb878e31c5c

It won't be pushed to chocolatey until I merge the changes into the master branch.

**Comment by sharkykh** [comment]
@AdmiringWorm 
Thank you very much for the explanations, and for solving the issues!

**Comment by AdmiringWorm** [comment]
@sharkykh no problem, the latest 6.x version have also been submitted to chocolatey, and should be available in a few hours.

**Comment by sharkykh** [comment]
@AdmiringWorm 
Just curious, it seems as though when I install it on an AppVeyor build it doesn't override the pre-installed version. Do you know why, or why the `ISCC.exe` shim still points to version 5 and not 6?
```
choco install -y --no-progress InnoSetup
Chocolatey v0.10.11
Installing the following packages:
InnoSetup
By installing you accept licenses for the packages.
chocolatey-core.extension v1.3.3 [Approved]
chocolatey-core.extension package files install completed. Performing other installation steps.
 Installed/updated chocolatey-core extensions.
 The install of chocolatey-core.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolatey-core'
InnoSetup v6.0.2 [Approved]
innosetup package files install completed. Performing other installation steps.
Installing innosetup...
innosetup has been installed.
innosetup installed to 'C:\Program Files (x86)\Inno Setup 5'
Added C:\ProgramData\chocolatey\bin\ISCC.exe shim pointed to 'c:\program files (x86)\inno setup 5\iscc.exe'.
  innosetup can be automatically uninstalled.
 The install of innosetup was successful.
  Software installed to 'C:\Program Files (x86)\Inno Setup 6\'
Chocolatey installed 2/2 packages.
```

**Comment by AdmiringWorm** [comment]
> Just curious, it seems as though when I install it on a AppVeyor build it doesn't override the pre-installed version.

That is unfortunately the installer that doesn't override the previous version, probably due to allowing them to be installed side by side.

> Do you know why, or why the ISCC.exe shim still points to version 5 and not 6?

That would be because the package itself don't know where the software gets installed, and the helper function I use to get the installation path picks up the version 5 of inno setup.

I will try to see if I can work around it, so it at least picks up the correct version, but that probably won't happen until Wednesday at the earliest unfortunately.

Temporary workaround you can use in the meantime:
```powershell
# Install the package without installing the software
choco install innosetup -n
# Uninstall the package would uninstall the software if it is already installed (only if just 1 instance have been installed).
choco uninstall innosetup
# Do a normal installation
choco install innosetup
```

**Pull request closed without merging**
